/*
 * generated by Xtext 2.32.0
 */
package org.xtext.example.mydsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.simplemio.ui.internal.SimplemioActivator;

public class SimpleMioUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return SimplemioActivator.getInstance().getInjector("org.xtext.example.mydsl.SimpleMio");
	}

}
