/*
 * generated by Xtext 2.34.0
 */
package org.xtext.example.mydsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class SimpleMioStandaloneSetup extends SimpleMioStandaloneSetupGenerated {

	public static void doSetup() {
		new SimpleMioStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
