/**
 * generated by Xtext 2.34.0
 */
package org.xtext.example.mydsl.formatting2;

import com.google.inject.Inject;
import java.util.Arrays;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;
import org.xtext.example.mydsl.services.SimpleMioGrammarAccess;
import simplemioModel.Event;
import simplemioModel.Model;
import simplemioModel.Program;

@SuppressWarnings("all")
public class SimpleMioFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private SimpleMioGrammarAccess _simpleMioGrammarAccess;

  protected void _format(final Model model, @Extension final IFormattableDocument document) {
    document.<Program>format(model.getProgram());
  }

  protected void _format(final Program program, @Extension final IFormattableDocument document) {
    EList<Event> _events = program.getEvents();
    for (final Event event : _events) {
      document.<Event>format(event);
    }
  }

  public void format(final Object model, final IFormattableDocument document) {
    if (model instanceof XtextResource) {
      _format((XtextResource)model, document);
      return;
    } else if (model instanceof Model) {
      _format((Model)model, document);
      return;
    } else if (model instanceof Program) {
      _format((Program)model, document);
      return;
    } else if (model instanceof EObject) {
      _format((EObject)model, document);
      return;
    } else if (model == null) {
      _format((Void)null, document);
      return;
    } else if (model != null) {
      _format(model, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(model, document).toString());
    }
  }
}
