/*
 * generated by Xtext 2.34.0
 */
package org.xtext.example.mydsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.mydsl.parser.antlr.internal.InternalSimpleMioParser;
import org.xtext.example.mydsl.services.SimpleMioGrammarAccess;

public class SimpleMioParser extends AbstractAntlrParser {

	@Inject
	private SimpleMioGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSimpleMioParser createParser(XtextTokenStream stream) {
		return new InternalSimpleMioParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public SimpleMioGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SimpleMioGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
