/*
 * generated by Xtext 2.32.0
 */
package org.xtext.example.mydsl.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.example.simplemio.ui.internal.SimplemioActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SimpleMioExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(SimplemioActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		SimplemioActivator activator = SimplemioActivator.getInstance();
		return activator != null ? activator.getInjector(SimplemioActivator.ORG_XTEXT_EXAMPLE_MYDSL_SIMPLEMIO) : null;
	}

}
